package dto

type CityParameters struct {
	Name       string `json:"name"`
	LocalNames struct {
		Mg          string `json:"mg,omitempty"`
		Uk          string `json:"uk,omitempty"`
		Sh          string `json:"sh,omitempty"`
		Tl          string `json:"tl,omitempty"`
		El          string `json:"el,omitempty"`
		Sl          string `json:"sl,omitempty"`
		Tt          string `json:"tt,omitempty"`
		Av          string `json:"av,omitempty"`
		He          string `json:"he"`
		Es          string `json:"es,omitempty"`
		Ascii       string `json:"ascii,omitempty"`
		Su          string `json:"su,omitempty"`
		To          string `json:"to,omitempty"`
		Nv          string `json:"nv,omitempty"`
		Ar          string `json:"ar,omitempty"`
		Ff          string `json:"ff,omitempty"`
		Be          string `json:"be,omitempty"`
		Kw          string `json:"kw,omitempty"`
		Da          string `json:"da,omitempty"`
		Kn          string `json:"kn,omitempty"`
		Bo          string `json:"bo,omitempty"`
		Sw          string `json:"sw,omitempty"`
		Ga          string `json:"ga,omitempty"`
		St          string `json:"st,omitempty"`
		Lb          string `json:"lb,omitempty"`
		Tw          string `json:"tw,omitempty"`
		Si          string `json:"si,omitempty"`
		My          string `json:"my,omitempty"`
		Sn          string `json:"sn,omitempty"`
		Ee          string `json:"ee,omitempty"`
		Io          string `json:"io,omitempty"`
		Sd          string `json:"sd,omitempty"`
		Sr          string `json:"sr,omitempty"`
		Sm          string `json:"sm,omitempty"`
		Cs          string `json:"cs,omitempty"`
		Km          string `json:"km,omitempty"`
		Nn          string `json:"nn,omitempty"`
		Eo          string `json:"eo,omitempty"`
		Rm          string `json:"rm,omitempty"`
		Ka          string `json:"ka,omitempty"`
		Ny          string `json:"ny,omitempty"`
		De          string `json:"de,omitempty"`
		Ms          string `json:"ms,omitempty"`
		Ig          string `json:"ig,omitempty"`
		Co          string `json:"co,omitempty"`
		Ia          string `json:"ia,omitempty"`
		Af          string `json:"af,omitempty"`
		Ab          string `json:"ab,omitempty"`
		Zu          string `json:"zu,omitempty"`
		Mt          string `json:"mt,omitempty"`
		Ha          string `json:"ha,omitempty"`
		Fo          string `json:"fo,omitempty"`
		It          string `json:"it,omitempty"`
		Cy          string `json:"cy,omitempty"`
		Ps          string `json:"ps,omitempty"`
		Li          string `json:"li,omitempty"`
		Zh          string `json:"zh,omitempty"`
		Uz          string `json:"uz,omitempty"`
		Eu          string `json:"eu,omitempty"`
		En          string `json:"en"`
		Kk          string `json:"kk,omitempty"`
		Sa          string `json:"sa,omitempty"`
		Oc          string `json:"oc,omitempty"`
		Os          string `json:"os,omitempty"`
		Ca          string `json:"ca,omitempty"`
		Fy          string `json:"fy,omitempty"`
		Ml          string `json:"ml,omitempty"`
		An          string `json:"an,omitempty"`
		Bh          string `json:"bh,omitempty"`
		Pl          string `json:"pl,omitempty"`
		Ne          string `json:"ne,omitempty"`
		Ht          string `json:"ht,omitempty"`
		No          string `json:"no,omitempty"`
		Ru          string `json:"ru"`
		Wo          string `json:"wo,omitempty"`
		Bn          string `json:"bn,omitempty"`
		Ja          string `json:"ja,omitempty"`
		Ku          string `json:"ku,omitempty"`
		Az          string `json:"az,omitempty"`
		Id          string `json:"id,omitempty"`
		Ro          string `json:"ro,omitempty"`
		Nl          string `json:"nl,omitempty"`
		Mk          string `json:"mk,omitempty"`
		Ko          string `json:"ko"`
		Pt          string `json:"pt,omitempty"`
		Lo          string `json:"lo,omitempty"`
		Ie          string `json:"ie,omitempty"`
		Bg          string `json:"bg,omitempty"`
		Yo          string `json:"yo,omitempty"`
		FeatureName string `json:"feature_name,omitempty"`
		Is          string `json:"is,omitempty"`
		Fi          string `json:"fi,omitempty"`
		Tk          string `json:"tk,omitempty"`
		Gn          string `json:"gn,omitempty"`
		Vo          string `json:"vo,omitempty"`
		Gd          string `json:"gd,omitempty"`
		Gl          string `json:"gl,omitempty"`
		So          string `json:"so,omitempty"`
		Te          string `json:"te,omitempty"`
		Or          string `json:"or,omitempty"`
		Fr          string `json:"fr"`
		Ba          string `json:"ba,omitempty"`
		Qu          string `json:"qu,omitempty"`
		Pa          string `json:"pa,omitempty"`
		Wa          string `json:"wa,omitempty"`
		Ce          string `json:"ce,omitempty"`
		Tg          string `json:"tg,omitempty"`
		Na          string `json:"na,omitempty"`
		Vi          string `json:"vi,omitempty"`
		Cu          string `json:"cu,omitempty"`
		Hy          string `json:"hy,omitempty"`
		Hi          string `json:"hi,omitempty"`
		Am          string `json:"am,omitempty"`
		Fj          string `json:"fj,omitempty"`
		Yi          string `json:"yi,omitempty"`
		Ta          string `json:"ta,omitempty"`
		Jv          string `json:"jv,omitempty"`
		Lv          string `json:"lv,omitempty"`
		Sv          string `json:"sv,omitempty"`
		Sq          string `json:"sq,omitempty"`
		Lt          string `json:"lt,omitempty"`
		Sk          string `json:"sk,omitempty"`
		Mr          string `json:"mr,omitempty"`
		Th          string `json:"th,omitempty"`
		Ky          string `json:"ky,omitempty"`
		Hu          string `json:"hu,omitempty"`
		Kl          string `json:"kl,omitempty"`
		Br          string `json:"br,omitempty"`
		Sc          string `json:"sc,omitempty"`
		Bi          string `json:"bi,omitempty"`
		Bm          string `json:"bm,omitempty"`
		Om          string `json:"om,omitempty"`
		Gv          string `json:"gv,omitempty"`
		Ln          string `json:"ln,omitempty"`
		Gu          string `json:"gu,omitempty"`
		Et          string `json:"et,omitempty"`
		Ay          string `json:"ay,omitempty"`
		Se          string `json:"se,omitempty"`
		Mi          string `json:"mi,omitempty"`
		Ur          string `json:"ur,omitempty"`
		Mn          string `json:"mn,omitempty"`
		Cv          string `json:"cv,omitempty"`
		Tr          string `json:"tr,omitempty"`
		Ug          string `json:"ug,omitempty"`
		Fa          string `json:"fa,omitempty"`
		Bs          string `json:"bs,omitempty"`
		Hr          string `json:"hr,omitempty"`
		Kv          string `json:"kv,omitempty"`
		Oj          string `json:"oj,omitempty"`
		Iu          string `json:"iu,omitempty"`
		Cr          string `json:"cr,omitempty"`
	} `json:"local_names,omitempty"`
	Lat     float64 `json:"lat"`
	Lon     float64 `json:"lon"`
	Country string  `json:"country"`
	State   string  `json:"state"`
}

type WeatherResp struct {
	Coord struct {
		Lon float64 `json:"lon"`
		Lat float64 `json:"lat"`
	} `json:"coord"`
	Weather []struct {
		Id          int    `json:"id"`
		Main        string `json:"main"`
		Description string `json:"description"`
		Icon        string `json:"icon"`
	} `json:"weather"`
	Base string `json:"base"`
	Main struct {
		Temp      float64 `json:"temp"`
		FeelsLike float64 `json:"feels_like"`
		TempMin   float64 `json:"temp_min"`
		TempMax   float64 `json:"temp_max"`
		Pressure  int     `json:"pressure"`
		Humidity  int     `json:"humidity"`
		SeaLevel  int     `json:"sea_level"`
		GrndLevel int     `json:"grnd_level"`
	} `json:"main"`
	Visibility int `json:"visibility"`
	Wind       struct {
		Speed float64 `json:"speed"`
		Deg   int     `json:"deg"`
		Gust  float64 `json:"gust"`
	} `json:"wind"`
	Rain struct {
		H float64 `json:"1h"`
	} `json:"rain"`
	Clouds struct {
		All int `json:"all"`
	} `json:"clouds"`
	Dt  int `json:"dt"`
	Sys struct {
		Type    int    `json:"type"`
		Id      int    `json:"id"`
		Country string `json:"country"`
		Sunrise int    `json:"sunrise"`
		Sunset  int    `json:"sunset"`
	} `json:"sys"`
	Timezone int    `json:"timezone"`
	Id       int    `json:"id"`
	Name     string `json:"name"`
	Cod      int    `json:"cod"`
}
